### ISSUE TITLE
Feature Request: Support Tickets

### ISSUE THREAD

**Issue by onenoteperpage** [OptechX/optechx.portal#90]
Create the support tickets area, where a user is able to create and update/add/close etc tickets.

There should be a list view of all their tickets in the Support section.

They should be able to click on a ticket to view it. Any updates should be added as chronological data to the end of each ticket, and updated showing who sent it, when it was sent.

If the ticket is marked as closed - it is locked.

**Comment by danijeljw-RPC** [comment]
Non-nullable field 'editContext' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
